on:
  schedule:
    - cron: '*/30 07/23 * * *'
  workflow_dispatch:  

jobs:
  ping_site:
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
    - name: Check the site
      id: hello
      uses: srt32/uptime@master
      with:
        url-to-hit: "http://iwan8n.herokuapp.com"
        expected-statuses: "200,301,401"
